WARNING: You're attempting to print out a bitcode file.
This is inadvisable as it may cause display problems. If
you REALLY want to taste LLVM bitcode first-hand, you
can force output with the `-f' option.

CallGraph Root is: main
Call graph node <<null function>><<0x2f18370>>  #uses=0
  CS<0x0> calls function 'main'
  CS<0x0> calls function 'printf'

Call graph node for function: 'main'<<0x2f18410>>  #uses=1
  CS<0x2f00840> calls function 'printf'

Call graph node for function: 'printf'<<0x2f00460>>  #uses=2
  CS<0x0> calls external node

