default:
	pdflatex description.tex
	

purge:
	rm -f   *.aux \
                *.dvi \
                *.out\
                *.log \
		description.pdf 

clean:
	rm -f   *.aux \
                *.out\
                *.dvi \
                *.log \
				


